package com.example.backend.Enums;

public enum UserRoles {
    ROLE_SUPER_ADMIN,       // MAN
    ROLE_ADMIN,   //TIZIM ADMINI
    ROLE_WORKER,  //MALUMOT TOLDIRUVCHI ISHCHI
    ROLE_AGENT,     //AGENT
    ROLE_OPERATOR,//OPERATOR
    ROLE_STUDENT,       //STUDENT
    ROLE_DATA_MANAGER,
    ROLE_AMBASSADOR,
    ROLE_ACCOUNTANT

}
